### ISSUE TITLE
lab3

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/akulov_proga#1]
Картинка хорошая, но 
1) неправильно оформлены докстринги (нужно использовать многострочный комментарий и т.д.)
2) отрисовка должна производиться в главном цикле. В данном случае это не очень важно, но, если будет какая-то динамика, то так работать не будет

**Comment by abacaba01** [comment]
нужно ли мне сейчас это исправлять?


пн, 5 окт. 2020 г. в 10:46, kolganovn <notifications@github.com>:

**Comment by kolganovn** [comment]
Да, задание сдано, если все issues закрыты

**Comment by abacaba01** [comment]
вроде бы все исправил
