### ISSUE TITLE
lab5/The\ game.py

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/akulov_proga#2]
Я думаю нужно стремиться к оригинальности не только за счет флексовой музыки.
Вообще, прога виснет после концы игры, это надо пофиксить. И сделать нормальные highscores.
Ещё нужно перед использованием pygame.mixer надо делать pygame.mixer.init()

**Comment by abacaba01** [comment]
Она не виснет, а ждет когда введут имя


вт, 13 окт. 2020 г., 23:09 kolganovn <notifications@github.com>:

**Comment by abacaba01** [comment]
исправил все
